### PR TITLE
Naming changes in project.

### PR DESCRIPTION
**Pull request by MichaelStergianis**
`magit-blame-mode-map` was changed to `blame-read-only-mode-map`
`magit-blame-read-only-mode` was added
`magit-error-section-map` was added

### CODE REVIEW

**Comment by mriehl** [comment]
Thanks for this, I was getting initialization errors related to the `magit-blame-mode-map` and this fixed it!

**Comment by kommen** [comment]
I can confirm this fixes #43

**Comment by FieryCod** [comment]
It's crucial to merge this.

**Comment by Paryz** [comment]
guys please 😄 without magit I feel handless 😢

**Comment by justbur** [comment]
Thanks!

**Comment by dennismayr** [comment]
I keep getting the exact same error 2 days after it was allegedly fixed.
Removed packages, let Spacemacs install them again, problem persists.

**Comment by adamfaryna** [comment]
I had to add `(defvar magit-blame-read-only-mode-map (make-sparse-keymap))` before (require 'evil-magit) to make it work. 

magit-20180406.1110
evil-magit-20180702.1553

**Pull request merged**
